replicas:
  drydock: 3

labels:
  api:
    node_selector_key: ucp-control-plane
    node_selector_value: enabled
  job:
    node_selector_key: ucp-control-plane
    node_selector_value: enabled

images:
  tags:
    drydock: quay.io/airshipit/drydock:master
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
    ks_user: docker.io/openstackhelm/heat:newton
    ks_service: docker.io/openstackhelm/heat:newton
    ks_endpoints: docker.io/openstackhelm/heat:newton
    drydock_db_init: docker.io/postgres:9.5
    drydock_db_sync: quay.io/airshipit/drydock:master

endpoints:
  identity:
    auth:
      admin:
        region_name: RegionOne
        project_name: admin
        password: password
        username: admin
        user_domain_name: default
        project_domain_name: default
      drydock:
        region_name: RegionOne
        role: admin
        project_name: service
        project_domain_name: default
        user_domain_name: default
        username: drydock
        password: password
  postgresql:
    name: postgresql
    auth:
      admin:
        username: postgres
        password: password
      user:
        username: drydock
        password: password
        database: drydock
  maas_region:
    name: maas-region
    auth:
      admin:
        username: admin
        password: admin
        email: none@none
    hosts:
      public: maas

